[package]
name = "fractal_renderer"
version = "0.1.4"
edition = "2021"

[dependencies]
bytemuck = "1.21.0"
fastrand = "2.2.0"
flume = "0.11.1"
image = { version = "0.25.5", default-features = false, features = [
    "png",
    "jpeg",
] }
num-complex = "0.4.6"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
wgpu = "23.0.1"
