[package]
name = "fractal_renderer"
version = "0.1.4"
edition = "2021"

[dependencies]
fastrand = "2.2.0"
image = { version = "0.25.5", default-features = false, features = [
    "png",
    "jpeg",
] }
rayon = "1.10.0"
ron = "0.8.1"
serde = { version = "1.0.215", features = ["derive"] }
uni-path = "1.51.1"
wide = "0.7.32"
